log_dir: "Checkpoint"
save_freq: 5
device: "cuda"
epochs: 200
batch_size: 32
pretrained_model: ""
train_data: "Data/Kaggle_ASR_Train_data.txt"
val_data: "Data/Kaggle_ASR_Val_data.txt"

preprocess_parasm:
  sr: 24000
  spect_params:
    n_fft: 1024
    win_length: 1024
    hop_length: 256
  mel_params:
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 80
   token_embedding_dim: 256

optimizer_params:
  lr: 0.0001
